import Foundation

/// `dependencies` — the project's own: `node_modules`, and `Pods` when the project
/// has a Podfile.
///
/// This is not the "no automatic provisioning" rule being bent. That rule is about
/// **host tools** — Xcode, iOS runtimes — which belong to the machine and to whoever
/// administers it. These two belong to the repo: gitignored, reinstallable, and
/// already described by a lockfile the project committed. CONTEXT.md draws the same
/// line, and it has to stay drawn in both places or the next reader reads this stage
/// as a violation.
public struct DependenciesStage: Stage {
    public let id = "dependencies"

    private let anchor: ProjectAnchor
    private let runner: any ProcessRunner
    /// Where each install's whole output goes — a failed one's ten lines are almost
    /// always the deprecation warnings the installer piled on after the reason (#49).
    private let logs: RunLogs

    public init(anchor: ProjectAnchor, runner: any ProcessRunner, logs: RunLogs? = nil) {
        self.anchor = anchor
        self.runner = runner
        self.logs = logs ?? RunLogs(project: anchor.directory)
    }

    public func run(_ context: inout UpContext) async throws -> StageOutcome {
        var installed: [String] = []
        // Node first: a Podfile generated by React Native reads its pods out of
        // node_modules, so the other order fails on a fresh clone.
        if try await installNode() { installed.append("node_modules") }
        if try await installPods() { installed.append("Pods") }

        return installed.isEmpty
            ? .skipped("already installed")
            : .pass("installed \(installed.joined(separator: " and "))")
    }

    /// Present or absent is the whole test. No comparison against the lockfile: it
    /// costs tens of seconds on every run, and a `node_modules` that has drifted from
    /// the lock is something the build says out loud anyway.
    ///
    /// Looked for where the install runs, not at the anchor. A hoisted workspace puts
    /// the packages in the **root's** `node_modules` and can leave the member with
    /// none at all — asking the member would reinstall the whole monorepo on every
    /// `up`, which is the cost this skip exists to avoid.
    private func installNode() async throws -> Bool {
        let command = anchor.installProcess
        let directory = command.workingDirectory ?? anchor.directory
        guard !FileManager.default.fileExists(
            atPath: directory.appendingPathComponent("node_modules").path
        ) else { return false }

        try await install(command, what: "node_modules", byHand: anchor.installCommand)
        return true
    }

    /// Only when there is a Podfile: a project that does not use CocoaPods is not
    /// punished for it with a stage that looks for files it will never have.
    private func installPods() async throws -> Bool {
        let ios = anchor.directory.appendingPathComponent("ios")
        guard FileManager.default.fileExists(atPath: ios.appendingPathComponent(Self.podfile).path),
            Self.podsAreStale(ios)
        else { return false }

        try await install(
            ProcessCommand("pod", ["install"], workingDirectory: ios, timeout: nil),
            what: "Pods",
            byHand: "cd \(ios.path) && pod install"
        )
        return true
    }

    /// CocoaPods' own rule, byte for byte: the manifest it copies next to `Pods/` has
    /// to be the lock it was built from. Comparing the versions inside would be a
    /// second opinion about somebody else's file format.
    ///
    /// Either file missing counts as stale — nothing has been installed here yet.
    private static func podsAreStale(_ ios: URL) -> Bool {
        func contents(_ relativePath: String) -> Data? {
            FileManager.default.contents(atPath: ios.appendingPathComponent(relativePath).path)
        }
        guard let lock = contents(podfileLock), let manifest = contents(manifestLock) else {
            return true
        }
        return lock != manifest
    }

    /// A failed install is a domain failure: the project's dependencies are the
    /// project's, so it lands on exit 1 next to a line the reader can paste. An
    /// install that could not be *started* throws `ProcessError` from the runner and
    /// goes out as exit 2 untouched.
    ///
    /// Streamed to a file for the reason `build` is (ADR-0002's note on #44/#56): an
    /// installer that fails says why somewhere, and the ten lines that fit on screen
    /// are the warnings it printed afterwards. The tail stays as the first thing to
    /// read; the file is where the reason actually is.
    private func install(_ command: ProcessCommand, what: String, byHand: String) async throws {
        var streamed = command
        let file = logs.url("\(command.executable)-install.log")
        streamed.output = .streamed(to: file)

        let tail = LineTail(limit: 10)
        let result = try await runner.run(streamed, onLine: { tail.append($0) })
        guard !result.terminationStatus.isSuccess else { return }
        throw DomainError(
            summary: "installing \(what) failed",
            observed: tail.text,
            remediation: Remediation(
                summary: "The whole install log is at \(file.path). "
                    + "An installer that fails usually says why in more lines than fit here.",
                command: byHand
            )
        )
    }

    private static let podfile = "Podfile"
    private static let podfileLock = "Podfile.lock"
    private static let manifestLock = "Pods/Manifest.lock"
}
