import Foundation

/// `dependencies` — the project's own: `node_modules`, and `Pods` when the project
/// has a Podfile.
///
/// This is not the "no automatic provisioning" rule being bent. That rule is about
/// **host tools** — Xcode, iOS runtimes — which belong to the machine and to whoever
/// administers it. These two belong to the repo: gitignored, reinstallable, and
/// already described by a lockfile the project committed. CONTEXT.md draws the same
/// line, and it has to stay drawn in both places or the next reader reads this stage
/// as a violation.
public struct DependenciesStage: Stage {
    public let id = "dependencies"

    private let anchor: ProjectAnchor
    private let runner: any ProcessRunner
    /// Where each install's whole output goes — a failed one's ten lines are almost
    /// always the deprecation warnings the installer piled on after the reason (#49).
    private let logs: RunLogs

    public init(anchor: ProjectAnchor, runner: any ProcessRunner, logs: RunLogs? = nil) {
        self.anchor = anchor
        self.runner = runner
        self.logs = logs ?? RunLogs(project: anchor.directory)
    }

    public func run(_ context: inout UpContext) async throws -> StageOutcome {
        var installed: [String] = []
        // Node first: a Podfile generated by React Native reads its pods out of
        // node_modules, so the other order fails on a fresh clone.
        if try await installNode() { installed.append("node_modules") }
        installed.append(contentsOf: try await installPods())

        return installed.isEmpty
            ? .skipped("already installed")
            : .pass("installed \(installed.joined(separator: " and "))")
    }

    /// Presence is the normal test. No comparison against the lockfile: it costs tens
    /// of seconds on every run, and a `node_modules` that has drifted from the lock is
    /// something the build says out loud anyway. The one exception is an install this
    /// stage saw fail: its marker stays behind until a later install succeeds.
    ///
    /// Looked for where the install runs, not at the anchor. A hoisted workspace puts
    /// the packages in the **root's** `node_modules` and can leave the member with
    /// none at all — asking the member would reinstall the whole monorepo on every
    /// `up`, which is the cost this skip exists to avoid.
    private func installNode() async throws -> Bool {
        let command = anchor.installProcess
        let directory = command.workingDirectory ?? anchor.directory
        let files = FileManager.default
        let nodeModules = directory.appendingPathComponent("node_modules")
        let incomplete = nodeModules.appendingPathComponent(".mobile-install.incomplete")
        guard !files.fileExists(atPath: nodeModules.path)
            || files.fileExists(atPath: incomplete.path)
        else { return false }

        func markIncomplete() throws {
            try files.createDirectory(at: nodeModules, withIntermediateDirectories: true)
            try Data().write(to: incomplete, options: .atomic)
        }

        try markIncomplete()
        do {
            try await install(command, what: "node_modules", byHand: anchor.installCommand)
        } catch let installError {
            try markIncomplete()
            throw installError
        }
        try? files.removeItem(at: incomplete)
        return true
    }

    /// Only when there is a Podfile: a project that does not use CocoaPods is not
    /// punished for it with a stage that looks for files it will never have.
    ///
    /// *How* the Pods get installed is the anchor's answer, not this stage's — a repo
    /// that declared its own pod install declared it because the bare one does not
    /// work there (#48).
    ///
    /// - Returns: what was installed, in the order it was — the gems come first when
    ///   they were missing, because the pod install is what needs them.
    private func installPods() async throws -> [String] {
        let ios = anchor.directory.appendingPathComponent("ios")
        guard FileManager.default.fileExists(atPath: ios.appendingPathComponent(Self.podfile).path),
            Self.podsAreStale(ios)
        else { return [] }

        var installed: [String] = []
        if try await installGems() { installed.append("gems") }

        try await install(
            anchor.podInstallProcess,
            what: "Pods",
            byHand: anchor.podInstallCommand,
            chosenBy: anchor.podInstallEvidence
        )
        installed.append("Pods")
        return installed
    }

    /// Only when the Pods are about to be installed, because that is what needs them:
    /// a declared pod install runs under `bundle exec`, and bundler stops before doing
    /// anything if a gem in the lock is missing (#59).
    ///
    /// `bundle check` is the staleness test — bundler's own question about bundler's
    /// own files. Parsing `Gemfile.lock` against the installed gems would be a second
    /// opinion about somebody else's format, the same reason `podsAreStale` compares
    /// the two lock files byte for byte instead of reading them.
    ///
    /// A `bundle` that cannot run at all is not this stage's failure to report: the
    /// pod install is about to run and will say what it needs in its own words. So
    /// the check's own inability is silence here, not exit 2.
    private func installGems() async throws -> Bool {
        guard let gems = anchor.gemInstallProcess, let byHand = anchor.gemInstallCommand
        else { return false }

        let check = ProcessCommand(
            "bundle", ["check"], workingDirectory: gems.workingDirectory, timeout: .seconds(60)
        )
        guard let checked = try? await runner.run(check), !checked.terminationStatus.isSuccess
        else { return false }

        try await install(
            gems, what: "gems", byHand: byHand, chosenBy: " `Gemfile` is what picks it."
        )
        return true
    }

    /// CocoaPods' own rule, byte for byte: the manifest it copies next to `Pods/` has
    /// to be the lock it was built from. Comparing the versions inside would be a
    /// second opinion about somebody else's file format.
    ///
    /// Either file missing counts as stale — nothing has been installed here yet.
    private static func podsAreStale(_ ios: URL) -> Bool {
        func contents(_ relativePath: String) -> Data? {
            FileManager.default.contents(atPath: ios.appendingPathComponent(relativePath).path)
        }
        guard let lock = contents(podfileLock), let manifest = contents(manifestLock) else {
            return true
        }
        return lock != manifest
    }

    /// A failed install is a domain failure: the project's dependencies are the
    /// project's, so it lands on exit 1 next to a line the reader can paste. An
    /// install that could not be *started* throws `ProcessError` from the runner and
    /// goes out as exit 2 untouched.
    ///
    /// Streamed to a file for the reason `build` is (ADR-0002's note on #44/#56): an
    /// installer that fails says why somewhere. Its known error spelling is preferred
    /// for the screen excerpt; the tail remains the fallback and the whole file stays
    /// available when no known spelling matches.
    ///
    /// The log is named after what is being installed, not after the installer that
    /// ran: a declared pod install goes through the same `yarn` the Node install did,
    /// and a name taken from the executable would have the second overwrite the first.
    ///
    /// - Parameter chosenBy: what picked `byHand`, when something did. A pasted
    ///   command carries the evidence that chose it (ADR-0003); empty when the command
    ///   is the default and there is no evidence to name.
    private func install(
        _ command: ProcessCommand, what: String, byHand: String, chosenBy: String = ""
    ) async throws {
        var streamed = command
        let file = logs.url("\(what)-install.log")
        streamed.output = .streamed(to: file)

        let excerpt = LineExcerpt(limit: 10, notable: Self.isNotableInstallFailure)
        let result = try await runner.run(streamed, onLine: { excerpt.append($0) })
        guard !result.terminationStatus.isSuccess else { return }
        throw DomainError(
            summary: "installing \(what) failed",
            observed: excerpt.text,
            remediation: Remediation(
                summary: "The whole install log is at \(file.path). "
                    + "An installer that fails usually says why in more lines than fit here."
                    + chosenBy,
                command: byHand
            )
        )
    }

    private static func isNotableInstallFailure(_ line: String) -> Bool {
        if line.hasPrefix("npm error ") { return true }
        if line.hasPrefix("➤ YN0000:"), line.contains("Error") { return true }
        guard !line.hasPrefix("from ") else { return false }
        return line.range(
            of: #"\([A-Z][A-Za-z0-9]*(?:::[A-Z][A-Za-z0-9]*)*\)$"#,
            options: .regularExpression
        ) != nil
    }

    private static let podfile = "Podfile"
    private static let podfileLock = "Podfile.lock"
    private static let manifestLock = "Pods/Manifest.lock"
}
