import Foundation
import TestSupport
import Testing

@testable import Core

/// The evidence chain behind the matrix input (ADR-0003): a measurement first, then
/// the lockfile an install already resolved, then an exact pin. A pristine clone has
/// no `node_modules`, and that is exactly the moment `git clone → mobile up` runs.
@Suite("react-native evidence chain")
struct ReactNativeVersionTests {
    private func resolved(_ repo: FixtureRepo, from relativePath: String = "") -> ReactNativeVersion? {
        let start = relativePath.isEmpty ? repo.root : repo.url(relativePath)
        return ProjectAnchor.detect(from: start)?.reactNativeVersion
    }

    private func npmLock(_ entries: String, version: Int = 3) -> String {
        """
        {"name": "app", "lockfileVersion": \(version), "packages": {\(entries)}}
        """
    }

    @Test("the measurement wins, and a lockfile that says otherwise is carried into the verdict")
    func measurementWins() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "^0.81.0"}}"#)
        try repo.write("node_modules/react-native/package.json", #"{"version": "0.81.6"}"#)
        try repo.write("package-lock.json", npmLock(#""node_modules/react-native": {"version": "0.81.4"}"#))

        let version = try #require(resolved(repo))

        #expect(version.value == "0.81.6")
        #expect(version.origin == "node_modules/react-native")
        #expect(version.disagreement == "package-lock.json resolves 0.81.4")
    }

    /// The common case: the install that wrote the lockfile is the same install the
    /// clone is missing, so the two agree and there is nothing to report.
    @Test("a lockfile agreeing with the measurement is not a disagreement")
    func lockfileAgrees() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "^0.81.0"}}"#)
        try repo.write("node_modules/react-native/package.json", #"{"version": "0.81.6"}"#)
        try repo.write("package-lock.json", npmLock(#""node_modules/react-native": {"version": "0.81.6"}"#))

        #expect(try #require(resolved(repo)).disagreement == nil)
    }

    @Test("a pristine clone resolves the version from package-lock.json")
    func npmLockfile() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "^0.81.0"}}"#)
        try repo.write("package-lock.json", npmLock(#""node_modules/react-native": {"version": "0.81.6"}"#))

        let version = try #require(resolved(repo))

        #expect(version.value == "0.81.6")
        #expect(version.origin == "package-lock.json")
    }

    /// npm hoists to the workspace root, but a version conflict keeps a copy next to
    /// the package that asked for it — and that copy is the one this anchor builds on.
    @Test("a nested workspace entry outranks the hoisted one")
    func npmLockfileNestedEntry() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"workspaces": ["packages/*"]}"#)
        try repo.write(
            "package-lock.json",
            npmLock(
                """
                "node_modules/react-native": {"version": "0.70.6"},
                "packages/app/node_modules/react-native": {"version": "0.81.6"}
                """
            )
        )
        try repo.write("packages/app/package.json", #"{"dependencies": {"react-native": "0.81.6"}}"#)

        #expect(resolved(repo, from: "packages/app")?.value == "0.81.6")
    }

    /// lockfileVersion 1 has no `packages` map. It answers nothing rather than
    /// wrongly — the chain drops to the next piece of evidence.
    @Test("a lockfileVersion 1 file is not evidence")
    func npmLockfileV1() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "^0.81.0"}}"#)
        try repo.write("package-lock.json", #"{"lockfileVersion": 1, "dependencies": {}}"#)

        #expect(resolved(repo) == nil)
    }

    /// joplin: two react-native entries in one `yarn.lock`, and a scan that takes the
    /// first one picks 0.70.6 for an app that builds on 0.81.6.
    @Test("yarn berry matches the anchor's own descriptor, not the first react-native entry")
    func yarnBerryDescriptorMatch() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"workspaces": ["packages/*"]}"#)
        try repo.write(
            "yarn.lock",
            """
            # This file is generated by running "yarn install" inside your project.

            __metadata:
              version: 8

            "react-native@npm:0.70.6":
              version: 0.70.6
              resolution: "react-native@npm:0.70.6"

            "react-native@npm:^0.81.0, react-native@npm:0.81.6":
              version: 0.81.6
              resolution: "react-native@npm:0.81.6"
            """
        )
        try repo.write("packages/app/package.json", #"{"dependencies": {"react-native": "0.81.6"}}"#)

        let version = try #require(resolved(repo, from: "packages/app"))

        #expect(version.value == "0.81.6")
        #expect(version.origin == "yarn.lock")
    }

    @Test("a yarn.lock with no entry for the anchor's descriptor answers nothing")
    func yarnBerryNoMatch() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "^0.82.0"}}"#)
        try repo.write(
            "yarn.lock",
            """
            "react-native@npm:0.81.6":
              version: 0.81.6
            """
        )

        #expect(resolved(repo) == nil)
    }

    /// pnpm and bun locks are not parsed (ADR-0003). The chain walks past them to the
    /// pin rather than treating the repo as unmeasurable.
    @Test("an unparsed lockfile kind still leaves the exact pin as evidence")
    func exactPin() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "0.81.6"}}"#)
        try repo.write("pnpm-lock.yaml", "lockfileVersion: '9.0'\n")

        let version = try #require(resolved(repo))

        #expect(version.value == "0.81.6")
        #expect(version.origin == "package.json dependencies.react-native")
    }

    /// The rule that started all this stands: `^0.81.0` says nothing about which minor
    /// is installed, and the matrix rows differ by minor.
    @Test("a range is not a pin, and with nothing else there is no version")
    func rangeIsNotEvidence() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "^0.81.0"}}"#)

        #expect(resolved(repo) == nil)
    }

    @Test("a partial version is a range in disguise and is not a pin")
    func partialVersionIsNotAPin() throws {
        let repo = try FixtureRepo()
        try repo.write("package.json", #"{"dependencies": {"react-native": "0.81"}}"#)

        #expect(resolved(repo) == nil)
    }
}
